[2025-05-19T14:00:26.625+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_bank_reviews.run_clean_reviews manual__2025-05-19T13:00:10.707380+00:00 [queued]>
[2025-05-19T14:00:26.644+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_bank_reviews.run_clean_reviews manual__2025-05-19T13:00:10.707380+00:00 [queued]>
[2025-05-19T14:00:26.646+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-19T14:00:26.686+0100] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_clean_reviews> on 2025-05-19 13:00:10.707380+00:00
[2025-05-19T14:00:26.699+0100] {standard_task_runner.py:60} INFO - Started process 78813 to run task
[2025-05-19T14:00:26.708+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'process_bank_reviews', 'run_clean_reviews', 'manual__2025-05-19T13:00:10.707380+00:00', '--job-id', '1922', '--raw', '--subdir', 'DAGS_FOLDER/post_processing.py', '--cfg-path', '/tmp/tmpqs2qn36f']
[2025-05-19T14:00:26.712+0100] {standard_task_runner.py:88} INFO - Job 1922: Subtask run_clean_reviews
[2025-05-19T14:00:26.846+0100] {task_command.py:423} INFO - Running <TaskInstance: process_bank_reviews.run_clean_reviews manual__2025-05-19T13:00:10.707380+00:00 [running]> on host DESKTOP-RRUTCI2.
[2025-05-19T14:00:27.066+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='process_bank_reviews' AIRFLOW_CTX_TASK_ID='run_clean_reviews' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T13:00:10.707380+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T13:00:10.707380+00:00'
[2025-05-19T14:00:27.071+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-19T14:00:27.074+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ~/airflow/dbt_project && dbt run --select clean_bank_reviews']
[2025-05-19T14:00:27.093+0100] {subprocess.py:86} INFO - Output:
[2025-05-19T14:01:12.914+0100] {subprocess.py:93} INFO - [0m13:01:12  Running with dbt=1.8.7
[2025-05-19T14:01:17.071+0100] {subprocess.py:93} INFO - [0m13:01:17  Registered adapter: postgres=1.8.2
[2025-05-19T14:01:22.706+0100] {subprocess.py:93} INFO - [0m13:01:22  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-05-19T14:01:22.710+0100] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-05-19T14:01:22.713+0100] {subprocess.py:93} INFO - - models.dbt_project.forPy
[2025-05-19T14:01:24.514+0100] {subprocess.py:93} INFO - [0m13:01:24  Found 8 models, 1 seed, 4 data tests, 1 source, 540 macros
[2025-05-19T14:01:24.521+0100] {subprocess.py:93} INFO - [0m13:01:24
[2025-05-19T14:01:33.902+0100] {subprocess.py:93} INFO - [0m13:01:33  Concurrency: 4 threads (target='dev')
[2025-05-19T14:01:33.909+0100] {subprocess.py:93} INFO - [0m13:01:33
[2025-05-19T14:01:33.916+0100] {subprocess.py:93} INFO - [0m13:01:33  1 of 1 START sql view model public.clean_bank_reviews .......................... [RUN]
[2025-05-19T14:01:34.158+0100] {subprocess.py:93} INFO - [0m13:01:34  1 of 1 OK created sql view model public.clean_bank_reviews ..................... [[32mCREATE VIEW[0m in 0.24s]
[2025-05-19T14:01:34.188+0100] {subprocess.py:93} INFO - [0m13:01:34
[2025-05-19T14:01:34.190+0100] {subprocess.py:93} INFO - [0m13:01:34  Finished running 1 view model in 0 hours 0 minutes and 9.67 seconds (9.67s).
[2025-05-19T14:01:34.427+0100] {subprocess.py:93} INFO - [0m13:01:34
[2025-05-19T14:01:34.433+0100] {subprocess.py:93} INFO - [0m13:01:34  [32mCompleted successfully[0m
[2025-05-19T14:01:34.437+0100] {subprocess.py:93} INFO - [0m13:01:34
[2025-05-19T14:01:34.440+0100] {subprocess.py:93} INFO - [0m13:01:34  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-05-19T14:01:35.685+0100] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-19T14:01:35.781+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_bank_reviews, task_id=run_clean_reviews, execution_date=20250519T130010, start_date=20250519T130026, end_date=20250519T130135
[2025-05-19T14:01:35.850+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-19T14:01:35.923+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
